<?php
/**
 * CallbacksApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Calcasa\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Copyright 2026 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).
 *
 * Contact: info@calcasa.nl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.23.0
 */
 
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Calcasa\Api\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Calcasa\Api\ApiException;
use Calcasa\Api\Configuration;
use Calcasa\Api\FormDataProcessor;
use Calcasa\Api\HeaderSelector;
use Calcasa\Api\ObjectSerializer;

/**
 * CallbacksApi Class Doc Comment
 *
 * @category Class
 * @package  Calcasa\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CallbacksApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'addOrUpdateCallbackSubscription' => [
            'application/json',
        ],
        'deleteNotificationSubscription' => [
            'application/json',
        ],
        'getNotificationSubscription' => [
            'application/json',
        ],
        'getNotificationSubscriptions' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation addOrUpdateCallbackSubscription
     *
     * Voeg een callback inschrijving toe (of werk bij) voor de huidige client voor een adres.
     *
     * @param  \Calcasa\Api\Model\CallbackInschrijving $callbackInschrijving De te configureren callback inschrijving. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addOrUpdateCallbackSubscription'] to see the possible values for this operation
     *
     * @throws \Calcasa\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Calcasa\Api\Model\CallbackInschrijving|\Calcasa\Api\Model\InvalidArgumentProblemDetails|\Calcasa\Api\Model\UnauthorizedProblemDetails|\Calcasa\Api\Model\PermissionsDeniedProblemDetails|\Calcasa\Api\Model\ProblemDetails
     */
    public function addOrUpdateCallbackSubscription($callbackInschrijving, string $contentType = self::contentTypes['addOrUpdateCallbackSubscription'][0])
    {
        list($response) = $this->addOrUpdateCallbackSubscriptionWithHttpInfo($callbackInschrijving, $contentType);
        return $response;
    }

    /**
     * Operation addOrUpdateCallbackSubscriptionWithHttpInfo
     *
     * Voeg een callback inschrijving toe (of werk bij) voor de huidige client voor een adres.
     *
     * @param  \Calcasa\Api\Model\CallbackInschrijving $callbackInschrijving De te configureren callback inschrijving. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addOrUpdateCallbackSubscription'] to see the possible values for this operation
     *
     * @throws \Calcasa\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Calcasa\Api\Model\CallbackInschrijving|\Calcasa\Api\Model\InvalidArgumentProblemDetails|\Calcasa\Api\Model\UnauthorizedProblemDetails|\Calcasa\Api\Model\PermissionsDeniedProblemDetails|\Calcasa\Api\Model\ProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function addOrUpdateCallbackSubscriptionWithHttpInfo($callbackInschrijving, string $contentType = self::contentTypes['addOrUpdateCallbackSubscription'][0])
    {
        $request = $this->addOrUpdateCallbackSubscriptionRequest($callbackInschrijving, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\CallbackInschrijving',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\InvalidArgumentProblemDetails',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\UnauthorizedProblemDetails',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\PermissionsDeniedProblemDetails',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\ProblemDetails',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Calcasa\Api\Model\CallbackInschrijving',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\CallbackInschrijving',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\InvalidArgumentProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\UnauthorizedProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\PermissionsDeniedProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation addOrUpdateCallbackSubscriptionAsync
     *
     * Voeg een callback inschrijving toe (of werk bij) voor de huidige client voor een adres.
     *
     * @param  \Calcasa\Api\Model\CallbackInschrijving $callbackInschrijving De te configureren callback inschrijving. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addOrUpdateCallbackSubscription'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addOrUpdateCallbackSubscriptionAsync($callbackInschrijving, string $contentType = self::contentTypes['addOrUpdateCallbackSubscription'][0])
    {
        return $this->addOrUpdateCallbackSubscriptionAsyncWithHttpInfo($callbackInschrijving, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation addOrUpdateCallbackSubscriptionAsyncWithHttpInfo
     *
     * Voeg een callback inschrijving toe (of werk bij) voor de huidige client voor een adres.
     *
     * @param  \Calcasa\Api\Model\CallbackInschrijving $callbackInschrijving De te configureren callback inschrijving. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addOrUpdateCallbackSubscription'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addOrUpdateCallbackSubscriptionAsyncWithHttpInfo($callbackInschrijving, string $contentType = self::contentTypes['addOrUpdateCallbackSubscription'][0])
    {
        $returnType = '\Calcasa\Api\Model\CallbackInschrijving';
        $request = $this->addOrUpdateCallbackSubscriptionRequest($callbackInschrijving, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'addOrUpdateCallbackSubscription'
     *
     * @param  \Calcasa\Api\Model\CallbackInschrijving $callbackInschrijving De te configureren callback inschrijving. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addOrUpdateCallbackSubscription'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function addOrUpdateCallbackSubscriptionRequest($callbackInschrijving, string $contentType = self::contentTypes['addOrUpdateCallbackSubscription'][0])
    {

        // verify the required parameter 'callbackInschrijving' is set
        if ($callbackInschrijving === null || (is_array($callbackInschrijving) && count($callbackInschrijving) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $callbackInschrijving when calling addOrUpdateCallbackSubscription'
            );
        }


        $resourcePath = '/callbacks/inschrijvingen';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($callbackInschrijving)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($callbackInschrijving));
            } else {
                $httpBody = $callbackInschrijving;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteNotificationSubscription
     *
     * Verwijder de callback inschrijving voor deze client, dit adres en optioneel een geldverstrekker.
     *
     * @param  int $bagNummeraanduidingId Het BAG Nummeraanduiding ID waar de callback inschrijving voor geldt. (required)
     * @param  string|null $geldverstrekker De naam van de geldverstrekker waar de callback inschrijving voor geldt. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteNotificationSubscription'] to see the possible values for this operation
     *
     * @throws \Calcasa\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteNotificationSubscription($bagNummeraanduidingId, $geldverstrekker = null, string $contentType = self::contentTypes['deleteNotificationSubscription'][0])
    {
        $this->deleteNotificationSubscriptionWithHttpInfo($bagNummeraanduidingId, $geldverstrekker, $contentType);
    }

    /**
     * Operation deleteNotificationSubscriptionWithHttpInfo
     *
     * Verwijder de callback inschrijving voor deze client, dit adres en optioneel een geldverstrekker.
     *
     * @param  int $bagNummeraanduidingId Het BAG Nummeraanduiding ID waar de callback inschrijving voor geldt. (required)
     * @param  string|null $geldverstrekker De naam van de geldverstrekker waar de callback inschrijving voor geldt. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteNotificationSubscription'] to see the possible values for this operation
     *
     * @throws \Calcasa\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteNotificationSubscriptionWithHttpInfo($bagNummeraanduidingId, $geldverstrekker = null, string $contentType = self::contentTypes['deleteNotificationSubscription'][0])
    {
        $request = $this->deleteNotificationSubscriptionRequest($bagNummeraanduidingId, $geldverstrekker, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\UnauthorizedProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\PermissionsDeniedProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\NotFoundProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteNotificationSubscriptionAsync
     *
     * Verwijder de callback inschrijving voor deze client, dit adres en optioneel een geldverstrekker.
     *
     * @param  int $bagNummeraanduidingId Het BAG Nummeraanduiding ID waar de callback inschrijving voor geldt. (required)
     * @param  string|null $geldverstrekker De naam van de geldverstrekker waar de callback inschrijving voor geldt. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteNotificationSubscription'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteNotificationSubscriptionAsync($bagNummeraanduidingId, $geldverstrekker = null, string $contentType = self::contentTypes['deleteNotificationSubscription'][0])
    {
        return $this->deleteNotificationSubscriptionAsyncWithHttpInfo($bagNummeraanduidingId, $geldverstrekker, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteNotificationSubscriptionAsyncWithHttpInfo
     *
     * Verwijder de callback inschrijving voor deze client, dit adres en optioneel een geldverstrekker.
     *
     * @param  int $bagNummeraanduidingId Het BAG Nummeraanduiding ID waar de callback inschrijving voor geldt. (required)
     * @param  string|null $geldverstrekker De naam van de geldverstrekker waar de callback inschrijving voor geldt. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteNotificationSubscription'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteNotificationSubscriptionAsyncWithHttpInfo($bagNummeraanduidingId, $geldverstrekker = null, string $contentType = self::contentTypes['deleteNotificationSubscription'][0])
    {
        $returnType = '';
        $request = $this->deleteNotificationSubscriptionRequest($bagNummeraanduidingId, $geldverstrekker, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteNotificationSubscription'
     *
     * @param  int $bagNummeraanduidingId Het BAG Nummeraanduiding ID waar de callback inschrijving voor geldt. (required)
     * @param  string|null $geldverstrekker De naam van de geldverstrekker waar de callback inschrijving voor geldt. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteNotificationSubscription'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteNotificationSubscriptionRequest($bagNummeraanduidingId, $geldverstrekker = null, string $contentType = self::contentTypes['deleteNotificationSubscription'][0])
    {

        // verify the required parameter 'bagNummeraanduidingId' is set
        if ($bagNummeraanduidingId === null || (is_array($bagNummeraanduidingId) && count($bagNummeraanduidingId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bagNummeraanduidingId when calling deleteNotificationSubscription'
            );
        }



        $resourcePath = '/callbacks/inschrijvingen/{bagNummeraanduidingId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $geldverstrekker,
            'geldverstrekker', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($bagNummeraanduidingId !== null) {
            $resourcePath = str_replace(
                '{bagNummeraanduidingId}',
                ObjectSerializer::toPathValue($bagNummeraanduidingId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getNotificationSubscription
     *
     * Haal de callback inschrijving op voor deze client, dit adres en eventueel opgegeven geldverstrekker.
     *
     * @param  int $bagNummeraanduidingId Het BAG Nummeraanduiding ID waar de callback inschrijving voor geldt. (required)
     * @param  string|null $geldverstrekker De naam van de geldverstrekker waar de callback inschrijving voor geldt. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNotificationSubscription'] to see the possible values for this operation
     *
     * @throws \Calcasa\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Calcasa\Api\Model\CallbackInschrijving|\Calcasa\Api\Model\UnauthorizedProblemDetails|\Calcasa\Api\Model\PermissionsDeniedProblemDetails|\Calcasa\Api\Model\NotFoundProblemDetails|\Calcasa\Api\Model\ProblemDetails
     */
    public function getNotificationSubscription($bagNummeraanduidingId, $geldverstrekker = null, string $contentType = self::contentTypes['getNotificationSubscription'][0])
    {
        list($response) = $this->getNotificationSubscriptionWithHttpInfo($bagNummeraanduidingId, $geldverstrekker, $contentType);
        return $response;
    }

    /**
     * Operation getNotificationSubscriptionWithHttpInfo
     *
     * Haal de callback inschrijving op voor deze client, dit adres en eventueel opgegeven geldverstrekker.
     *
     * @param  int $bagNummeraanduidingId Het BAG Nummeraanduiding ID waar de callback inschrijving voor geldt. (required)
     * @param  string|null $geldverstrekker De naam van de geldverstrekker waar de callback inschrijving voor geldt. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNotificationSubscription'] to see the possible values for this operation
     *
     * @throws \Calcasa\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Calcasa\Api\Model\CallbackInschrijving|\Calcasa\Api\Model\UnauthorizedProblemDetails|\Calcasa\Api\Model\PermissionsDeniedProblemDetails|\Calcasa\Api\Model\NotFoundProblemDetails|\Calcasa\Api\Model\ProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function getNotificationSubscriptionWithHttpInfo($bagNummeraanduidingId, $geldverstrekker = null, string $contentType = self::contentTypes['getNotificationSubscription'][0])
    {
        $request = $this->getNotificationSubscriptionRequest($bagNummeraanduidingId, $geldverstrekker, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\CallbackInschrijving',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\UnauthorizedProblemDetails',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\PermissionsDeniedProblemDetails',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\NotFoundProblemDetails',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\ProblemDetails',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Calcasa\Api\Model\CallbackInschrijving',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\CallbackInschrijving',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\UnauthorizedProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\PermissionsDeniedProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\NotFoundProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getNotificationSubscriptionAsync
     *
     * Haal de callback inschrijving op voor deze client, dit adres en eventueel opgegeven geldverstrekker.
     *
     * @param  int $bagNummeraanduidingId Het BAG Nummeraanduiding ID waar de callback inschrijving voor geldt. (required)
     * @param  string|null $geldverstrekker De naam van de geldverstrekker waar de callback inschrijving voor geldt. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNotificationSubscription'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNotificationSubscriptionAsync($bagNummeraanduidingId, $geldverstrekker = null, string $contentType = self::contentTypes['getNotificationSubscription'][0])
    {
        return $this->getNotificationSubscriptionAsyncWithHttpInfo($bagNummeraanduidingId, $geldverstrekker, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getNotificationSubscriptionAsyncWithHttpInfo
     *
     * Haal de callback inschrijving op voor deze client, dit adres en eventueel opgegeven geldverstrekker.
     *
     * @param  int $bagNummeraanduidingId Het BAG Nummeraanduiding ID waar de callback inschrijving voor geldt. (required)
     * @param  string|null $geldverstrekker De naam van de geldverstrekker waar de callback inschrijving voor geldt. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNotificationSubscription'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNotificationSubscriptionAsyncWithHttpInfo($bagNummeraanduidingId, $geldverstrekker = null, string $contentType = self::contentTypes['getNotificationSubscription'][0])
    {
        $returnType = '\Calcasa\Api\Model\CallbackInschrijving';
        $request = $this->getNotificationSubscriptionRequest($bagNummeraanduidingId, $geldverstrekker, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getNotificationSubscription'
     *
     * @param  int $bagNummeraanduidingId Het BAG Nummeraanduiding ID waar de callback inschrijving voor geldt. (required)
     * @param  string|null $geldverstrekker De naam van de geldverstrekker waar de callback inschrijving voor geldt. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNotificationSubscription'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getNotificationSubscriptionRequest($bagNummeraanduidingId, $geldverstrekker = null, string $contentType = self::contentTypes['getNotificationSubscription'][0])
    {

        // verify the required parameter 'bagNummeraanduidingId' is set
        if ($bagNummeraanduidingId === null || (is_array($bagNummeraanduidingId) && count($bagNummeraanduidingId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bagNummeraanduidingId when calling getNotificationSubscription'
            );
        }



        $resourcePath = '/callbacks/inschrijvingen/{bagNummeraanduidingId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $geldverstrekker,
            'geldverstrekker', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($bagNummeraanduidingId !== null) {
            $resourcePath = str_replace(
                '{bagNummeraanduidingId}',
                ObjectSerializer::toPathValue($bagNummeraanduidingId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getNotificationSubscriptions
     *
     * Haal de callback inschrijvingen binnen voor deze client.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNotificationSubscriptions'] to see the possible values for this operation
     *
     * @throws \Calcasa\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Calcasa\Api\Model\CallbackInschrijving[]|\Calcasa\Api\Model\UnauthorizedProblemDetails|\Calcasa\Api\Model\PermissionsDeniedProblemDetails|\Calcasa\Api\Model\ProblemDetails
     */
    public function getNotificationSubscriptions(string $contentType = self::contentTypes['getNotificationSubscriptions'][0])
    {
        list($response) = $this->getNotificationSubscriptionsWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getNotificationSubscriptionsWithHttpInfo
     *
     * Haal de callback inschrijvingen binnen voor deze client.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNotificationSubscriptions'] to see the possible values for this operation
     *
     * @throws \Calcasa\Api\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Calcasa\Api\Model\CallbackInschrijving[]|\Calcasa\Api\Model\UnauthorizedProblemDetails|\Calcasa\Api\Model\PermissionsDeniedProblemDetails|\Calcasa\Api\Model\ProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function getNotificationSubscriptionsWithHttpInfo(string $contentType = self::contentTypes['getNotificationSubscriptions'][0])
    {
        $request = $this->getNotificationSubscriptionsRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\CallbackInschrijving[]',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\UnauthorizedProblemDetails',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\PermissionsDeniedProblemDetails',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Calcasa\Api\Model\ProblemDetails',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Calcasa\Api\Model\CallbackInschrijving[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\CallbackInschrijving[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\UnauthorizedProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\PermissionsDeniedProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Calcasa\Api\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getNotificationSubscriptionsAsync
     *
     * Haal de callback inschrijvingen binnen voor deze client.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNotificationSubscriptions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNotificationSubscriptionsAsync(string $contentType = self::contentTypes['getNotificationSubscriptions'][0])
    {
        return $this->getNotificationSubscriptionsAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getNotificationSubscriptionsAsyncWithHttpInfo
     *
     * Haal de callback inschrijvingen binnen voor deze client.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNotificationSubscriptions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNotificationSubscriptionsAsyncWithHttpInfo(string $contentType = self::contentTypes['getNotificationSubscriptions'][0])
    {
        $returnType = '\Calcasa\Api\Model\CallbackInschrijving[]';
        $request = $this->getNotificationSubscriptionsRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getNotificationSubscriptions'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNotificationSubscriptions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getNotificationSubscriptionsRequest(string $contentType = self::contentTypes['getNotificationSubscriptions'][0])
    {


        $resourcePath = '/callbacks/inschrijvingen';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
