<?php
/**
 * Gebiedsdata
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Calcasa\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Copyright 2025 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).
 *
 * The version of the OpenAPI document: 1.4.0-rc1
 * Contact: info@calcasa.nl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.13.0
 */
 
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Calcasa\Api\Model;

use \ArrayAccess;
use \Calcasa\Api\ObjectSerializer;

/**
 * Gebiedsdata Class Doc Comment
 *
 * @category Class
 * @package  Calcasa\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Gebiedsdata implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Gebiedsdata';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'naam' => 'string',
        'gemiddeldePrijsEengezinswoningen' => 'int',
        'gemiddeldePrijsMeergezinswoningen' => 'int',
        'gemiddeldeVierkantemeterPrijsEengezinswoningen' => 'int',
        'gemiddeldeVierkantemeterPrijsMeergezinswoningen' => 'int',
        'prijsveranderingAfgelopenJaar' => 'int',
        'prijsveranderingAfgelopen3Jaar' => 'int',
        'prijsveranderingAfgelopen5Jaar' => 'int',
        'prijsveranderingAfgelopen10Jaar' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'naam' => null,
        'gemiddeldePrijsEengezinswoningen' => 'int32',
        'gemiddeldePrijsMeergezinswoningen' => 'int32',
        'gemiddeldeVierkantemeterPrijsEengezinswoningen' => 'int32',
        'gemiddeldeVierkantemeterPrijsMeergezinswoningen' => 'int32',
        'prijsveranderingAfgelopenJaar' => 'int32',
        'prijsveranderingAfgelopen3Jaar' => 'int32',
        'prijsveranderingAfgelopen5Jaar' => 'int32',
        'prijsveranderingAfgelopen10Jaar' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'naam' => false,
        'gemiddeldePrijsEengezinswoningen' => true,
        'gemiddeldePrijsMeergezinswoningen' => true,
        'gemiddeldeVierkantemeterPrijsEengezinswoningen' => true,
        'gemiddeldeVierkantemeterPrijsMeergezinswoningen' => true,
        'prijsveranderingAfgelopenJaar' => true,
        'prijsveranderingAfgelopen3Jaar' => true,
        'prijsveranderingAfgelopen5Jaar' => true,
        'prijsveranderingAfgelopen10Jaar' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'naam' => 'naam',
        'gemiddeldePrijsEengezinswoningen' => 'gemiddeldePrijsEengezinswoningen',
        'gemiddeldePrijsMeergezinswoningen' => 'gemiddeldePrijsMeergezinswoningen',
        'gemiddeldeVierkantemeterPrijsEengezinswoningen' => 'gemiddeldeVierkantemeterPrijsEengezinswoningen',
        'gemiddeldeVierkantemeterPrijsMeergezinswoningen' => 'gemiddeldeVierkantemeterPrijsMeergezinswoningen',
        'prijsveranderingAfgelopenJaar' => 'prijsveranderingAfgelopenJaar',
        'prijsveranderingAfgelopen3Jaar' => 'prijsveranderingAfgelopen3Jaar',
        'prijsveranderingAfgelopen5Jaar' => 'prijsveranderingAfgelopen5Jaar',
        'prijsveranderingAfgelopen10Jaar' => 'prijsveranderingAfgelopen10Jaar'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'naam' => 'setNaam',
        'gemiddeldePrijsEengezinswoningen' => 'setGemiddeldePrijsEengezinswoningen',
        'gemiddeldePrijsMeergezinswoningen' => 'setGemiddeldePrijsMeergezinswoningen',
        'gemiddeldeVierkantemeterPrijsEengezinswoningen' => 'setGemiddeldeVierkantemeterPrijsEengezinswoningen',
        'gemiddeldeVierkantemeterPrijsMeergezinswoningen' => 'setGemiddeldeVierkantemeterPrijsMeergezinswoningen',
        'prijsveranderingAfgelopenJaar' => 'setPrijsveranderingAfgelopenJaar',
        'prijsveranderingAfgelopen3Jaar' => 'setPrijsveranderingAfgelopen3Jaar',
        'prijsveranderingAfgelopen5Jaar' => 'setPrijsveranderingAfgelopen5Jaar',
        'prijsveranderingAfgelopen10Jaar' => 'setPrijsveranderingAfgelopen10Jaar'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'naam' => 'getNaam',
        'gemiddeldePrijsEengezinswoningen' => 'getGemiddeldePrijsEengezinswoningen',
        'gemiddeldePrijsMeergezinswoningen' => 'getGemiddeldePrijsMeergezinswoningen',
        'gemiddeldeVierkantemeterPrijsEengezinswoningen' => 'getGemiddeldeVierkantemeterPrijsEengezinswoningen',
        'gemiddeldeVierkantemeterPrijsMeergezinswoningen' => 'getGemiddeldeVierkantemeterPrijsMeergezinswoningen',
        'prijsveranderingAfgelopenJaar' => 'getPrijsveranderingAfgelopenJaar',
        'prijsveranderingAfgelopen3Jaar' => 'getPrijsveranderingAfgelopen3Jaar',
        'prijsveranderingAfgelopen5Jaar' => 'getPrijsveranderingAfgelopen5Jaar',
        'prijsveranderingAfgelopen10Jaar' => 'getPrijsveranderingAfgelopen10Jaar'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('naam', $data ?? [], null);
        $this->setIfExists('gemiddeldePrijsEengezinswoningen', $data ?? [], null);
        $this->setIfExists('gemiddeldePrijsMeergezinswoningen', $data ?? [], null);
        $this->setIfExists('gemiddeldeVierkantemeterPrijsEengezinswoningen', $data ?? [], null);
        $this->setIfExists('gemiddeldeVierkantemeterPrijsMeergezinswoningen', $data ?? [], null);
        $this->setIfExists('prijsveranderingAfgelopenJaar', $data ?? [], null);
        $this->setIfExists('prijsveranderingAfgelopen3Jaar', $data ?? [], null);
        $this->setIfExists('prijsveranderingAfgelopen5Jaar', $data ?? [], null);
        $this->setIfExists('prijsveranderingAfgelopen10Jaar', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['gemiddeldePrijsEengezinswoningen']) && ($this->container['gemiddeldePrijsEengezinswoningen'] < 0)) {
            $invalidProperties[] = "invalid value for 'gemiddeldePrijsEengezinswoningen', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['gemiddeldePrijsMeergezinswoningen']) && ($this->container['gemiddeldePrijsMeergezinswoningen'] < 0)) {
            $invalidProperties[] = "invalid value for 'gemiddeldePrijsMeergezinswoningen', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['gemiddeldeVierkantemeterPrijsEengezinswoningen']) && ($this->container['gemiddeldeVierkantemeterPrijsEengezinswoningen'] < 0)) {
            $invalidProperties[] = "invalid value for 'gemiddeldeVierkantemeterPrijsEengezinswoningen', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['gemiddeldeVierkantemeterPrijsMeergezinswoningen']) && ($this->container['gemiddeldeVierkantemeterPrijsMeergezinswoningen'] < 0)) {
            $invalidProperties[] = "invalid value for 'gemiddeldeVierkantemeterPrijsMeergezinswoningen', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets naam
     *
     * @return string|null
     */
    public function getNaam()
    {
        return $this->container['naam'];
    }

    /**
     * Sets naam
     *
     * @param string|null $naam naam
     *
     * @return self
     */
    public function setNaam($naam)
    {
        if (is_null($naam)) {
            throw new \InvalidArgumentException('non-nullable naam cannot be null');
        }
        $this->container['naam'] = $naam;

        return $this;
    }

    /**
     * Gets gemiddeldePrijsEengezinswoningen
     *
     * @return int|null
     */
    public function getGemiddeldePrijsEengezinswoningen()
    {
        return $this->container['gemiddeldePrijsEengezinswoningen'];
    }

    /**
     * Sets gemiddeldePrijsEengezinswoningen
     *
     * @param int|null $gemiddeldePrijsEengezinswoningen In hele euros.
     *
     * @return self
     */
    public function setGemiddeldePrijsEengezinswoningen($gemiddeldePrijsEengezinswoningen)
    {
        if (is_null($gemiddeldePrijsEengezinswoningen)) {
            array_push($this->openAPINullablesSetToNull, 'gemiddeldePrijsEengezinswoningen');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gemiddeldePrijsEengezinswoningen', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($gemiddeldePrijsEengezinswoningen) && ($gemiddeldePrijsEengezinswoningen < 0)) {
            throw new \InvalidArgumentException('invalid value for $gemiddeldePrijsEengezinswoningen when calling Gebiedsdata., must be bigger than or equal to 0.');
        }

        $this->container['gemiddeldePrijsEengezinswoningen'] = $gemiddeldePrijsEengezinswoningen;

        return $this;
    }

    /**
     * Gets gemiddeldePrijsMeergezinswoningen
     *
     * @return int|null
     */
    public function getGemiddeldePrijsMeergezinswoningen()
    {
        return $this->container['gemiddeldePrijsMeergezinswoningen'];
    }

    /**
     * Sets gemiddeldePrijsMeergezinswoningen
     *
     * @param int|null $gemiddeldePrijsMeergezinswoningen In hele euros.
     *
     * @return self
     */
    public function setGemiddeldePrijsMeergezinswoningen($gemiddeldePrijsMeergezinswoningen)
    {
        if (is_null($gemiddeldePrijsMeergezinswoningen)) {
            array_push($this->openAPINullablesSetToNull, 'gemiddeldePrijsMeergezinswoningen');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gemiddeldePrijsMeergezinswoningen', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($gemiddeldePrijsMeergezinswoningen) && ($gemiddeldePrijsMeergezinswoningen < 0)) {
            throw new \InvalidArgumentException('invalid value for $gemiddeldePrijsMeergezinswoningen when calling Gebiedsdata., must be bigger than or equal to 0.');
        }

        $this->container['gemiddeldePrijsMeergezinswoningen'] = $gemiddeldePrijsMeergezinswoningen;

        return $this;
    }

    /**
     * Gets gemiddeldeVierkantemeterPrijsEengezinswoningen
     *
     * @return int|null
     */
    public function getGemiddeldeVierkantemeterPrijsEengezinswoningen()
    {
        return $this->container['gemiddeldeVierkantemeterPrijsEengezinswoningen'];
    }

    /**
     * Sets gemiddeldeVierkantemeterPrijsEengezinswoningen
     *
     * @param int|null $gemiddeldeVierkantemeterPrijsEengezinswoningen In hele euros per vierkante meter.
     *
     * @return self
     */
    public function setGemiddeldeVierkantemeterPrijsEengezinswoningen($gemiddeldeVierkantemeterPrijsEengezinswoningen)
    {
        if (is_null($gemiddeldeVierkantemeterPrijsEengezinswoningen)) {
            array_push($this->openAPINullablesSetToNull, 'gemiddeldeVierkantemeterPrijsEengezinswoningen');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gemiddeldeVierkantemeterPrijsEengezinswoningen', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($gemiddeldeVierkantemeterPrijsEengezinswoningen) && ($gemiddeldeVierkantemeterPrijsEengezinswoningen < 0)) {
            throw new \InvalidArgumentException('invalid value for $gemiddeldeVierkantemeterPrijsEengezinswoningen when calling Gebiedsdata., must be bigger than or equal to 0.');
        }

        $this->container['gemiddeldeVierkantemeterPrijsEengezinswoningen'] = $gemiddeldeVierkantemeterPrijsEengezinswoningen;

        return $this;
    }

    /**
     * Gets gemiddeldeVierkantemeterPrijsMeergezinswoningen
     *
     * @return int|null
     */
    public function getGemiddeldeVierkantemeterPrijsMeergezinswoningen()
    {
        return $this->container['gemiddeldeVierkantemeterPrijsMeergezinswoningen'];
    }

    /**
     * Sets gemiddeldeVierkantemeterPrijsMeergezinswoningen
     *
     * @param int|null $gemiddeldeVierkantemeterPrijsMeergezinswoningen In hele euros per vierkante meter.
     *
     * @return self
     */
    public function setGemiddeldeVierkantemeterPrijsMeergezinswoningen($gemiddeldeVierkantemeterPrijsMeergezinswoningen)
    {
        if (is_null($gemiddeldeVierkantemeterPrijsMeergezinswoningen)) {
            array_push($this->openAPINullablesSetToNull, 'gemiddeldeVierkantemeterPrijsMeergezinswoningen');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gemiddeldeVierkantemeterPrijsMeergezinswoningen', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($gemiddeldeVierkantemeterPrijsMeergezinswoningen) && ($gemiddeldeVierkantemeterPrijsMeergezinswoningen < 0)) {
            throw new \InvalidArgumentException('invalid value for $gemiddeldeVierkantemeterPrijsMeergezinswoningen when calling Gebiedsdata., must be bigger than or equal to 0.');
        }

        $this->container['gemiddeldeVierkantemeterPrijsMeergezinswoningen'] = $gemiddeldeVierkantemeterPrijsMeergezinswoningen;

        return $this;
    }

    /**
     * Gets prijsveranderingAfgelopenJaar
     *
     * @return int|null
     */
    public function getPrijsveranderingAfgelopenJaar()
    {
        return $this->container['prijsveranderingAfgelopenJaar'];
    }

    /**
     * Sets prijsveranderingAfgelopenJaar
     *
     * @param int|null $prijsveranderingAfgelopenJaar In hele procenten.
     *
     * @return self
     */
    public function setPrijsveranderingAfgelopenJaar($prijsveranderingAfgelopenJaar)
    {
        if (is_null($prijsveranderingAfgelopenJaar)) {
            array_push($this->openAPINullablesSetToNull, 'prijsveranderingAfgelopenJaar');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('prijsveranderingAfgelopenJaar', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['prijsveranderingAfgelopenJaar'] = $prijsveranderingAfgelopenJaar;

        return $this;
    }

    /**
     * Gets prijsveranderingAfgelopen3Jaar
     *
     * @return int|null
     */
    public function getPrijsveranderingAfgelopen3Jaar()
    {
        return $this->container['prijsveranderingAfgelopen3Jaar'];
    }

    /**
     * Sets prijsveranderingAfgelopen3Jaar
     *
     * @param int|null $prijsveranderingAfgelopen3Jaar In hele procenten.
     *
     * @return self
     */
    public function setPrijsveranderingAfgelopen3Jaar($prijsveranderingAfgelopen3Jaar)
    {
        if (is_null($prijsveranderingAfgelopen3Jaar)) {
            array_push($this->openAPINullablesSetToNull, 'prijsveranderingAfgelopen3Jaar');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('prijsveranderingAfgelopen3Jaar', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['prijsveranderingAfgelopen3Jaar'] = $prijsveranderingAfgelopen3Jaar;

        return $this;
    }

    /**
     * Gets prijsveranderingAfgelopen5Jaar
     *
     * @return int|null
     */
    public function getPrijsveranderingAfgelopen5Jaar()
    {
        return $this->container['prijsveranderingAfgelopen5Jaar'];
    }

    /**
     * Sets prijsveranderingAfgelopen5Jaar
     *
     * @param int|null $prijsveranderingAfgelopen5Jaar In hele procenten.
     *
     * @return self
     */
    public function setPrijsveranderingAfgelopen5Jaar($prijsveranderingAfgelopen5Jaar)
    {
        if (is_null($prijsveranderingAfgelopen5Jaar)) {
            array_push($this->openAPINullablesSetToNull, 'prijsveranderingAfgelopen5Jaar');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('prijsveranderingAfgelopen5Jaar', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['prijsveranderingAfgelopen5Jaar'] = $prijsveranderingAfgelopen5Jaar;

        return $this;
    }

    /**
     * Gets prijsveranderingAfgelopen10Jaar
     *
     * @return int|null
     */
    public function getPrijsveranderingAfgelopen10Jaar()
    {
        return $this->container['prijsveranderingAfgelopen10Jaar'];
    }

    /**
     * Sets prijsveranderingAfgelopen10Jaar
     *
     * @param int|null $prijsveranderingAfgelopen10Jaar In hele procenten.
     *
     * @return self
     */
    public function setPrijsveranderingAfgelopen10Jaar($prijsveranderingAfgelopen10Jaar)
    {
        if (is_null($prijsveranderingAfgelopen10Jaar)) {
            array_push($this->openAPINullablesSetToNull, 'prijsveranderingAfgelopen10Jaar');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('prijsveranderingAfgelopen10Jaar', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['prijsveranderingAfgelopen10Jaar'] = $prijsveranderingAfgelopen10Jaar;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


