<?php
/**
 * OutboundFileSetState
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Calcasa\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Copyright 2025 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).
 *
 * Contact: info@calcasa.nl
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.16.0
 */
 
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Calcasa\Api\Model;
use \Calcasa\Api\ObjectSerializer;

/**
 * OutboundFileSetState Class Doc Comment
 *
 * @category Class
 * @description Outbound file set states.  | Value | Description | | --- | --- | | &#x60;preparing&#x60; | File set is being prepared for download. | | &#x60;ready&#x60; | File set is ready and is waiting for the files to be downloaded. | | &#x60;deleted&#x60; | File set has been downloaded and has been deleted. | | &#x60;expired&#x60; | File set has expired and all its contents have been deleted. |
 * @package  Calcasa\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OutboundFileSetState
{
    /**
     * Possible values of this enum
     */
    public const PREPARING = 'preparing';

    public const READY = 'ready';

    public const DELETED = 'deleted';

    public const EXPIRED = 'expired';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PREPARING,
            self::READY,
            self::DELETED,
            self::EXPIRED
        ];
    }
}


